### ISSUE TITLE
stopped working about 1 month ago

### ISSUE THREAD

**Issue by zoff99** [microg/NominatimGeocoderBackend#4] opened 2015-10-31 19:32 UTC
it was working fine. now about 1 month ago it does not give any results.
tested on 2 devices.

logcat will follow soon ...

**Comment by zoff99** [comment] 2015-11-07 14:10
java.io.FileNotFoundException: http://open.mapquestapi.com/nominatim/v1/search?format=json&accept-language=de&addressdetails=1&bounded=1&q=london&limit=3
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
    at org.microg.nlp.backend.nominatim.BackendService$AsyncGetRequest.run(BackendService.java:189)
java.lang.NullPointerException: Attempt to get length of null array
    at java.lang.String.<init>(String.java:119)
    at org.microg.nlp.backend.nominatim.BackendService$AsyncGetRequest.retrieveString(BackendService.java:220)
    at org.microg.nlp.backend.nominatim.BackendService.getFromLocationName(BackendService.java:99)
    at org.microg.nlp.api.GeocoderBackendService$Backend.getFromLocationName(GeocoderBackendService.java:80)
    at org.microg.nlp.api.GeocoderBackend$Stub.onTransact(GeocoderBackend.java:85)

**Comment by zoff99** [comment] 2015-11-07 14:12
http://open.mapquestapi.com/nominatim/

All Nominatim and Xapi requests require a key starting September 15, 2015.

Please visit the MapQuest Developer Network to sign up for an AppKey if you do not have one.

**Comment by zoff99** [comment] 2015-11-07 14:38
just change in source:

`private static String nominatim_key = "-----your-key-here-------";`

`private static String REVERSE_GEOCODE_URL =  "%sreverse?key="+nominatim_key+"&format=json&accept-language=%s&lat=%f&lon=%f";`

`private static String SEARCH_GEOCODE_URL =  "%ssearch?key="+nominatim_key+"&format=json&accept-language=%s&addressdetails=1&bounded=1&q=%s&limit=%d";`

`private static String SEARCH_GEOCODE_WITH_BOX_URL = "%ssearch?key="+nominatim_key+"&format=json&accept-language=%s&addressdetails=1&bounded=1&q=%s&limit=%d" + "&viewbox=%f,%f,%f,%f";`

and later make a text input field for users to enter their key after installation!

**Comment by gjedeer** [comment] 2015-11-22 13:35
Thanks for this solution mate!

**Comment by Catfriend1** [comment] 2015-12-20 21:37
Where can i get a new APK, please?

**Comment by n76** [comment] 2016-02-05 07:04
Definitely a problem and it is keeping a number of the apps and widgets I have from working properly. Fortunately the fix @zoff99 poste on Nov 7, 2015 fixes it for me. But I'd much rather have an APK off of F-Droid or the MicroG project page than one I build myself.

Would a pull request for a patch based on the comment @zoff99 help? 

Seems like the developer should be the one to get an App Key, but then the issue is where to put it as you'd probably not want it in the git source repository. And it isn't really kind to require each user to get their own app key.

**Comment by zoff99** [comment] 2016-02-08 13:37
only real solution would be to have a settings screen where every user needs to enter their personal API key. and this is then saved and used.
otherwise 1 API key for ALL users would generate too much requests, and some will be blocked (free service has some limits on how many requests can be made per timespan)

**Comment by gjedeer** [comment] 2016-02-08 14:55
I've started a discussion with them, let's see if they care

https://developer.mapquest.com/forum/android-backend

**Comment by Teyro** [comment] 2016-08-04 08:20
Hi there, i was wondering why it doenst work.... tryed to compile by myself with the patches but i am to stupid.... Can someone compile it for me?

**Comment by ArchangeGabriel** [comment] 2017-01-29 14:59
This should be fixed by the next build now that #14 landed.

**Comment by ale5000-git** [comment] 2017-02-05 12:46
@mar-v-in: I don't want to be annoying but now that the most important problem has been fixed is it possible to release a new version so F-Droid will pick it?

**Comment by mar-v-in** [comment] 2017-02-06 11:18
Release 1.2.0 just went live and should be available on F-Droid ~tomorrow

**Closed as completed by mar-v-in** 2017-02-06 11:18 UTC
